### ISSUE TITLE
CommsSender.stop may cause deadlock

### ISSUE THREAD

**Issue by cyrille-artho** [eclipse-paho/paho.mqtt.java#207]
Jun Yoneyawa from the University of Tokyo analyzed Paho rev. 496f94a58a41557ba2401d4ba94bc099a75ba8ef against Moquette version 0.7, and found a situation where "stop" can deadlock Paho. The analysis was carried out with Java Pathfinder, which can find deadlocks that may not occur often during normal execution but may happen in cases where a system is under heavy load. A partial error trace is attached below.

The problem is as follows:
1. Thread 8 keeps running as long as "running" is true (CommsSender.java:93, run).
2. Thread 11 calls "stop", which sets "running" to false, and eventually calls queueLock.notifyAll(). In CommsSender.java:68, stop, ClientState.java:1204, notifyQueueLock.
3. Thread 8 waits on that queueLock to receive an update from other threads such as thread 11, in ClientState.java:627, get.

The intention of the programmer is that thread 11 fires its signal _after_ thread 8 waits. However, such a timing is not guaranteed, hence a deadlock is possible if thread 11 is "too fast".

The code also has the problem that shared data, in this case "running" is accessed by multiple threads without using the same lock. Thread 11 uses lock "lifecycle" while thread 8 uses no lock. This can create a data race even if the deadlock above is fixed.

A fix therefore needs to do the following:
1. All accesses to each shared data item should be guarded by a common lock. This lock does not have to be the same global lock for each shared variable in case multiple shared variables (other than "running" exist).
2. The use of wait/notify has to tolerate timings where "wait" is called after the signal sent by "notify" has already expired. Typically, this involved re-checking the condition (such as "running") before calling notify. The entire code that checks condition or changes a variable that affects that condition, needs to be protected by a common lock. In this case, adding the line of code with "FIX" in the comment, just before wait(), avoids the deadlock (but not the data race):
   protected MqttWireMessage get() throws MqttException { // internal.ClientState.java:627
   ...
   synchronized(queueLock) { 
     ...
     try {
       ...
       if (!running) break; // FIX: re-check condition to avoid potential deadlock
       queueLock.wait();

Avoiding the data race requires more modifications, in particular in run() in internal/CommsSender.java:93 and in stop() in internal/CommsSender.java:68, and any other place where "running" is accessed. Each access has to be protected by a common lock.
Adding these locks may make the code less efficient, so a larger redesign may be necessary.

[paho-trace.txt](https://github.com/eclipse/paho.mqtt.java/files/267480/paho-trace.txt)

**Comment by dobermai** [comment]
We see this deadlock problem a lot, most often when connecting the client. This is especially a problem in environments with very low latency where a CONNACK can return (and thus a notify() happens) before Paho gets a chance to wait().

Unfortunately it seems there is no way to recover from the deadlock.

**Comment by tatemz** [comment]
Not sure if this is related... I have experienced deadlock from un-notified Token `responseLock` objects that were in the `WAITING` state.

Turns out, there was an `EOFException` that was being caused by our multiple clients having the same Client ID.

MQTT Brokers prematurely close any connections that are open with a Client ID if another connection with the same Client ID comes in.

By [ensuring unique Client IDs](https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttAsyncClient.java#L1275-L1280), my MQTT servers stopped closing the connections

**Comment by larrywalker** [comment]
Interesting, but we see this even when generating unique client ids.  There are multiple clients on multiple machines, so I guess there is a possibility of multiple machines generating the clientID, but down to the nanosecond is pretty unlikely for duplicate clientIds.

**Comment by jbalakrishna** [comment]
@tatemz  clientId was the issue in my case, got fixed after giving unique clientId

Thanks !

**Comment by sumitatflo** [comment]
@tatemz I get the same error. However in my case it would be necessary to maintain same clientId. If I generate a new clientId, it would mean the messages directed to old clientId (while the user was not connected, because of no internet available for example) would be lost because clientId has changed.
Any way to resolve this?

**Comment by icraggs** [comment]
There are several issues here.  I'm going to start with some of them.

1) The _running_ variable is conflating two uses: a) indicating whether the thread is running and b) signalling that it should stop.  I propose that only the run() method in each case should alter the value of the _running_ variable.  Another variable, toStop or similar, is used to signal that the run() method should terminate.  toStop is only written by the stop method if running is true, and is reset by the run() method when it terminates.

2) It's probably better that the start method for each of these threads waits until _running_ is true (set by the run() method, to make sure the thread actually starts.  If it doesn't after some interval then an exception can be thrown so that we don't carry on if a thread fails to start.  Likewise the stop method should probably wait until the thread it applies to has set _running_ to false.

I think these changes should fix the main issue described by @cyrille-artho.  I'm not sure that the issue described by @dobermai has the same cause - I've been looking at the code and can't find an obvious way that could happen yet.

**Comment by icraggs** [comment]
I've put a change into the develop branch that addresses this problem.  The initial failing test was on an unrelated timing issue which I've addressed now.

**Comment by icraggs** [comment]
Fix released in 1.2.1

**Comment by sumitatflo** [comment]
@sumit this has been fixed.
