### ISSUE TITLE
Can paho.mqtt.java connect the aws IoT's mqtt?

### ISSUE THREAD

**Issue by songqilong** [eclipse-paho/paho.mqtt.java#222]
Hi :
    I want to try to use paho.mqtt.java to connect to the AWS IoT's MQTTrecently.But I failed.AWS IoT seems to use the certificate and key to connect the server.Through the API of paho I can not find about this part.I also search the internet,but nothing.Can you offer me something document.

**Comment by jpwsutton** [comment]
Hi,
In order to use certificates, you'll need to create your own SSLSocketFactory. Once you've done this, you can then tell the Paho Java client to use it in MqttConnectOptions.setSocketFactory() (https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttConnectOptions.java#L289)

Take a look at these resources to see how you can create your own SSLSocketFactory that contains a client certificate:
- https://gist.github.com/sharonbn/4104301
- http://stackoverflow.com/questions/12997559/ssl-connection-from-java-client-eclipse-paho-to-mosquitto-broker-unknown-ca
- https://www.snip2code.com/Snippet/675419/A-simple-java-code-for-SSL-TLS-connectio

**Comment by songqilong** [comment]
Mr. Sutton:

```
   Thank you for your reply.This is what I want.It's very helpful to me!

   Thanks a lot!

                                                                                                     by Sql Song
```

---

发件人: James Sutton notifications@github.com
发送时间: 2016年7月27日 8:47
收件人: eclipse/paho.mqtt.java
抄送: songqilong; Author
主题: Re: [eclipse/paho.mqtt.java] Can paho.mqtt.java connect the aws IoT's mqtt? (#222)

Hi,
In order to use certificates, you'll need to create your own SSLSocketFactory. Once you've done this, you can then tell the Paho Java client to use it in MqttConnectOptions.setSocketFactory() (https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttConnectOptions.java#L289)

Take a look at these resources to see how you can create your own SSLSocketFactory that contains a client certificate:
-   https://gist.github.com/sharonbn/4104301
-   http://stackoverflow.com/questions/12997559/ssl-connection-from-java-client-eclipse-paho-to-mosquitto-broker-unknown-ca
-   https://www.snip2code.com/Snippet/675419/A-simple-java-code-for-SSL-TLS-connectio

―
