### ISSUE TITLE
Bugs in DisconnectedMessageBuffer Functionality

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.java#224]
Please fill out the form below before submitting, thank you!
- [x] Bug exists Release Version 1.1.0 ( Master Branch)
- [x] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please rasie the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

Initial message on paho-dev@eclipse.org mailing list:

Hi all,

I have been experimenting the Java client and in particular the disconnected publishing feature with file-based persistence and have come across a couple of issues (may be user error or I have misunderstood something):
1. ```
     I notice the DisconnectedBufferOptions.isPersistBuffer() method isn’t used – presumably the persistence scheme specified or defaulted by the MqttAsyncClient constructors is used?
   ```
2. ```
      Publishing messages when the client is in a disconnected state and using file based persistence I can see sb-0.msg is created on disk, however this file is overwritten for every message because the MqttWireMessage’s messageId field is not updated, this is used in the ClientState. getSendBufferedPersistenceKey method to construct the filename.
   ```
3. ```
     The ClientState. unPersistBufferedMessage method is only called during a reconnect, first time connections will not read buffered messages from the disk persistence store and are leaked (well, 1 is leaked because I only have a maximum of 1 message due to #2.). Note if I cause the client to disconnect then on re-connection in the ClientComms.notifyReconnect method the message is still not unpersisted in (i.e. deleted from disk) because there isn’t a matching messageId with index 0 in the DisconnectedMessageBuffer array.
   ```

Any help or guidance much appreciated, am happy to provide mode detail for #2 and #3 if needed.

Cheers,

Mark.

After further investigation:
1. isPersistBuffer is indeed not used. ClientComms should check this before persisting buffered messages (Around here: https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java-templates/org/eclipse/paho/client/mqttv3/internal/ClientComms.java#L153)
2. Looks like we increment the message ID after setting the persistence key, refactor needed: https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/ClientState.java#L564
3. More testing needed, but need to make sure that persisted messages are picked up when the application starts.

**Comment by jpwsutton** [comment]
After looking through my code I've got some more thoughts on part 3, unPersistBufferedMessage is not called when the client starts on purpose. This is because the persistence layer treats all persisted messages the same when a new client starts.
There is a test for this here: https://github.com/eclipse/paho.mqtt.java/blob/develop/org.eclipse.paho.client.mqttv3.test/src/test/java/org/eclipse/paho/client/mqttv3/test/automaticReconnect/OfflineBufferingTest.java#L406 which is passing.

I've got a fix for the first two errors, so I'll put that in now and see if that resolves the problem (As mismatched IDs would likely cause some issues)

**Comment by markjanstice** [comment]
Ahh, that's a fair point on part 3. I'll give those fixes a go, thanks James.

**Comment by jpwsutton** [comment]
No worries, they should be in the 1.1.1-SNAPSHOT tomorrow morning. Let me know how you get on.

**Comment by markjanstice** [comment]
In haste I cloned and built from your fork's develop branch and have had a partial success! 

1) I think in ClientComms.sendNoWait you also need to check disconnectedMessageBuffer.isPersistBuffer() in the disconnectedMessageBuffer != null && isResting() case - as using my test client application I can see new .msg files being persisted to the file system after shutting down my broker with isPersistBuffer=false.

2) The incrementing message id change means I now see sb-XXX.msg files created on the file system, when a new client starts up these messages are successfully published. 

However they are never deleted from the file system so every new client republishes them. I think this is because in the ClientState.notifyComplete method the persistence.remove call is passing in the result from getSendPersistenceKey which will always return s-XXX which doesn't exist - you would need to call getSendBufferedPersistenceKey instead. Not sure how you would determine which one to call though.

**Comment by markjanstice** [comment]
3) By the way In the unit test https://github.com/eclipse/paho.mqtt.java/blob/develop/org.eclipse.paho.client.mqttv3.test/src/test/java/org/eclipse/paho/client/mqttv3/test/automaticReconnect/OfflineBufferingTest.java#L406 if you change the message QoS from 0 to 1 the test fails. 

QoS 1 causes ClientState.notifyComplete to process the MqttPubAck message which calls persistence.remove(getSendPersistenceKey(message)) - of course this tries to remove s-0 from  TestMemoryPersistence which it wont't find (as sb-0 is explicitly put at the start of the test), the assert that postConnectKeys.size() is 0 is false therefore the test fails.

The reason why the QoS 0 message succeeds is because it is removed from persistence when the second client starts up where ClientState.restoreState calls persistence.remove for QoS 0 messages.

**Comment by jpwsutton** [comment]
1. Thanks for pointing that out, I've added that fix to my commit.
2. Yes!... Damn. 
3. Good spot, I'll look into a fix for that as well

**Comment by markjanstice** [comment]
James - I can confirm that those fixes have addressed the issues. Many thanks!
