### ISSUE TITLE
Could not allocate JNI Env on CommsReceiver

### ISSUE THREAD

**Issue by baole** [eclipse-paho/paho.mqtt.java#227]
Please fill out the form below before submitting, thank you!
- [v] Bug exists Release Version 1.1.0 ( Master Branch)
- [v] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

This issues raise on my production app via Fabric. I could not reproduce on my test environment.

```
Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.start(Unknown Source:64)
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(Unknown Source:652)
       at java.lang.Thread.run(Thread.java:818)
```

Occurred on Android 5.x, 6.x. Here is the crash report details: http://crashes.to/s/0c9c7ada6e8

**Comment by jpwsutton** [comment]
The Exception is being thrown when the CommsReceiver is attempting to start it's background thread but when requesting a new thread from the Android JNI, it's hitting this error: https://android.googlesource.com/platform/art/+/master/runtime/thread.cc#685

I've not seen this happen anywhere else due to just the Paho library on either Java or Android. Does your application use a lot of threads itself? It might help to run the application tethered to the Android Device monitor to help track down why you are running out of memory.
For instance, using the Example Application, I can see that it is using on average about 16MB
 of memory.

<img width="648" alt="screen shot 2016-08-01 at 14 06 15" src="https://cloud.githubusercontent.com/assets/1068763/17294854/2df49166-57f1-11e6-994d-ea5edbb8e0db.png">

**Comment by baole** [comment]
My app uses a few threads to call RESTful API (using AsyncTask) and download/render photos (using Glide library) from backend. The detail report from Fabric shows that the free memory ranges from 20-30%.

**Comment by jpwsutton** [comment]
If I'm reading the fabric report correctly, then there are hundreds of MQTT threads running, this is very odd but would explain the exception, It almost looks like many instances of the client have been started by the application somehow.

**Comment by baole** [comment]
This happens when the MQTT is disconnected and reconnected multiple times due to network changed. My app creates multiple MqttAndroidClient instances. Is it safe to reuse ( such as call connect() again) a MqttAndroidClient instance after disconnected? (sorry, this question should be probably posted on Android related project)

**Comment by jpwsutton** [comment]
The Android service will automatically try and re-connect for you when the network changes so you might not need to do this manually. It shouldn't be creating multiple instances of itself, so I suggest you look at how your application deals with the MqttAndroidClient. If you are creating a new version every time the connection changes then you'll want to either stop that from happening or safely disconnect, close and stop the old MqttAndroidClient objects before creating your new instance.

**Comment by baole** [comment]
Thank you.
