### ISSUE TITLE
Paho Java client used for android, get about connect Lost about every 3-4min.

### ISSUE THREAD

**Issue by gallex** [eclipse-paho/paho.mqtt.java#270]
- [x] Bug exists Release Version 1.0.2 ( Master Branch)

Yes, it is under Android , but I just only use NORMAL JAVA lib, so I put here.

the stranger is : when connected DEVICE to ADT, every thing is OK, otherwise it would lost connection about every 3-4min. 

after debug :  I found the error is cause by readMqttWireMessage(), when perform in.readByte() is get a EOFEception.

**Comment by gallex** [comment]
I found reason: 

the default KeepAlive option is 60s,  this is effect on both Server and Client.  that means server (or client  ) would close the connect  no packet received after  2*KeepAlive time  (is correct ?), normally it' fine because client would send a Ping packet every KeepAlive time .  But android client would sleep,  ping ping packet would send delay,   so the race between Server and Android Client ,  server always win:  it close the connection. 

Set  KeepAlive time big than  android wake up delay may resolve the problem. As for my test, 300s is OK.

**Comment by jpwsutton** [comment]
As I understand it, your problem is that Android puts the application to sleep which causes it to stop sending pings thus causing the server to close the connection. Unfortunately this is something that we can't really fix. Android M & N is very aggressive in preventing CPU usage and Network usage by applications when the device thinks it's not being used. (https://github.com/eclipse/paho.mqtt.android/issues/104)

You should look at making your app handle disconnects better and also take advantage of the automatic reconnect functionality. If you need your application to receive messages even when it is dozing, it seems that you can either get your app whitelisted (Which is not recommended), or use GCM (Google Cloud Messaging) to poke your app to wake up and connect to the mqtt broker.

**Comment by RemyEE** [comment]
Set keep alive interval to 300s work for me also.
