### ISSUE TITLE
Asynch client not logging published messages with QoT > 0

### ISSUE THREAD

**Issue by albertoanguita** [eclipse-paho/paho.mqtt.java#272]
Hi,

I have an aynch mqtt client (version 1.2.0). I implemented the MqttCallback deliveryComplete as follows:

``` java
@Override
public void deliveryComplete(IMqttDeliveryToken iMqttDeliveryToken) {
    if (LOGGER.isInfoEnabled()) {
        try {
            LOGGER.info("Message sent via MQTT: " + iMqttDeliveryToken.getMessage());
        } catch (MqttException e) {
            if (LOGGER.isWarnEnabled()) {
                LOGGER.warn("Message sent via MQTT could not be logged");
            }
        }
    }
}
```

If i use the mqtt client to publish a message with QoT = 0, then it is logged as expected. However, if QoT is 1 or 2, all logs show null. I traced the issue and found that this is due to the markComplete(MqttWireMessage msg, MqttException ex) method in Token being invoked before the message is logged, and thus the message object in Token is set to null.

Please fill out the form below before submitting, thank you!
- [x ] Bug exists Release Version 1.1.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please rasie the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

**Comment by jpwsutton** [comment]
Hi, that sounds like expected behaviour: https://www.eclipse.org/paho/files/javadoc/index.html

"Until the message has been delivered, the message being delivered will be returned. Once the message has been delivered null will be returned."

If you want to track which messages have been delivered, maybe use token.getMessageId() instead?

The reason QoS 0 messages worked for you is that due to the nature of QoS 0, there is no confirmation that the message has actually been delivered fully.

**Comment by albertoanguita** [comment]
Ok thanks. Sorry about bringing it up.
