### ISSUE TITLE
Use of System.currentTimeMillis() for measuring elapsed time

### ISSUE THREAD

**Issue by kamilfb** [eclipse-paho/paho.mqtt.java#278]
When measuring elapsed time in the ClientState class (and possibly in other places too), the code makes use of System.currentTimeMillis(). The problem is that the value returned by the System.currentTimeMillis() can be affected by system clock adjustments in the OS. 

For example, the time can jump forward/backward by quite a lot, which in turn might be interpreted as a timeout or expiry. The consequence of that can be unnecessary disconnections from the broker, or inability to recover from broken connections.

To measure elapsed time correctly, we should be using System.nanoTime().

**Comment by jpwsutton** [comment]
@kamilfb Thanks for adding this, Unfortunately because of the current JRE 1.4.2 requirement, we can't use System.nanoTime().

How urgently do you think we need to fix this? We could either try and find a 1.4.2 compatible solution, or I could schedule this for after the 1.3.0 release after which we will be targeting JRE 1.7 and above.

**Comment by jpwsutton** [comment]
Moving to backlog, we're now in Java 1.7 and above, so this task should be possible, however it will need to be carefully tested as it will mess with timing logic.

**Comment by jpwsutton** [comment]
After far too long, I've finally sat down and made the relevant changes to move from currentTimeMillis to nanoTime. I've also updated the relevant tests to use nanoTime as well.

The only thing that I think might need looking at in the future, is the use of the delta in ClientState.checkForActivity which seems to have been added in the past as a workaround to deal with inaccuracies caused by currentTimeMillis. A further piece of work may be required to remove this possibly unnecessary workaround.
