### ISSUE TITLE
NPE 

### ISSUE THREAD

**Issue by jotish** [eclipse-paho/paho.mqtt.java#337]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.1.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

<img width="768" alt="screen shot 2017-03-09 at 8 38 42 pm" src="https://cloud.githubusercontent.com/assets/3390136/23756240/0d1506b8-0509-11e7-8bc4-7ff0882afe89.png">

FIX

`MqttAsyncClient.java:1120`
```java
	private void stopReconnectCycle(){
		String methodName = "stopReconnectCycle";
		//@Trace 504=Stop reconnect timer for client: {0}
		log.fine(CLASS_NAME, methodName, "504", new Object[]{this.clientId});
		if (reconnectTimer != null) {
			reconnectTimer.cancel();
		}
		reconnectDelay = 1000; // Reset Delay Timer
		
	}
```

**Comment by jpwsutton** [comment]
Hi,

This has already been fixed in the develop branch: https://github.com/eclipse/paho.mqtt.java/blob/develop/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttAsyncClient.java#L1216 

You can get this fix by using a SNAPSHOT build or, by waiting for a service release that is due in the next week or so.

**Comment by jotish** [comment]
@jpwsutton Thanks for the update.
