### ISSUE TITLE
Isn't it nice to support message buffering before initial connect ?

### ISSUE THREAD

**Issue by matsukaz** [eclipse-paho/paho.mqtt.java#352]
Hi, I'm currently using paho.mqtt.java/paho.mqtt.android for Android App and also https://github.com/ckrey/MQTT-Client-Framework for iOS App.

MQTT-Client-Framework is supporting message buffering not only when connection is reconnected but also before initial connect.
This means after you create MqttAsyncClient instance, you can publish any messages even if connection is not yet established.

I've fixed the code to support this issue in my repo's branch.
What do you think about this ?
Could it be merged if I create pr ?

https://github.com/matsukaz/paho.mqtt.java/tree/message_buffering_before_connect

**Comment by jpwsutton** [comment]
Thanks for the contribution, opening a PR against our develop branch would be great. This is a behaviour that we originally opted against allowing when the buffering code was added, but a fair few people have asked for it over the last year so it should probably be allowed as I don't think there is any technical reason why we should limit developers in this way.

**Comment by icraggs** [comment]
The reason for not allowing it in the first place was, what if the URI or some other configuration was invalid?  You could be sending messages, thinking they were being sent, when they weren't, and weren't going anywhere ever.  This seemed dangerous.

**Comment by matsukaz** [comment]
Yes, I understand your concern.

My thinking is that, if you want to ensure your messsages to be sent immediately and correctly, you should check your connection by using IMqttActionListener's callback when you connect or call isConnected() method before you publish.
I guess most people are doing this and buffering messages by own selves if you need to send it later, or just ignoring unsent messages.

The point is that current library doesn't buffer messages before initial connect but does buffer if it's  disconnected.
Library users have to handle whether this is first connect or not, and have to implement original buffering if you need.

If library always buffer messages, we only have to know if connection is connected or not if you want to send messages immediately and correctly. No original buffering.

**Comment by matsukaz** [comment]
I've been created my pr here.
https://github.com/eclipse/paho.mqtt.java/pull/354

**Comment by maartenl945** [comment]
I understand the reason for not allowing buffering before the first connect as well, but unfortunately this situation than also occurs when the broker is not available on a fresh restart of the device. Because it seems like a first connect with the paho library, but it really isn't. The URI has been verified and proven to be working by that time already. Or am I wrong ?
This then forces paho users to implement their own buffering on top of the paho buffering which does not work in all situations.
So I would prefer buffering to be available before first connect as well, and leave it to the paho users to handle and watch for initial connect failures in some other way.

**Comment by rajeefmk** [comment]
+1 to this. 

Since I was facing an issue (reported here https://github.com/eclipse/paho.mqtt.android/issues/166 ), I had to set automaticreconnect to false. Because of this, the DisconnectedBuffer stopped working (I'm assuming because isResting() method returns false). 

isResting() method is set to true only for automaticreconnects I believe ? 

From ClientComms.java - 


		/**
	 * When Automatic reconnect is enabled, we want ClientComs to enter the
	 * 'resting' state if disconnected. This will allow us to publish messages
	 * @param resting
	 */
	public void setRestingState(boolean resting) {
		this.resting = resting;
	}
