### ISSUE TITLE
mvn build issue: java\org\eclipse\paho\client\mqttv3\ScheduledExecutorPingSender.java:28: error: reference not found

### ISSUE THREAD

**Issue by dubnemo** [eclipse-paho/paho.mqtt.java#426]
Please fill out the form below before submitting, thank you!

- [ X] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

mvn package -DskipTests
Returns:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project org.eclipse.paho.client.mqttv3: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\src\main\java\org\eclipse\paho\client\mqttv3\ScheduledExecutorPingSender.java:28: error: reference not found
[ERROR] * <p>This class implements the {@link IMqttPingSender} pinger interface
[ERROR] ^
[ERROR] C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\src\main\java-templates\org\eclipse\paho\client\mqttv3\internal\ClientComms.java:210: warning: no @param for force
[ERROR] public void close(boolean force) throws MqttException {
[ERROR] ^
[ERROR]
[ERROR] Command line was: C:\oracle\Java\jdk1.8.0_131\jre\..\bin\javadoc.exe @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\target\apidocs' dir.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project org.eclipse.paho.client.mqttv3: MavenReportException: Error while generating Javadoc:
Exit code: 1 - C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\src\main\java\org\eclipse\paho\client\mqttv3\ScheduledExecutorPingSender.java:28: error: reference not found
 * <p>This class implements the {@link IMqttPingSender} pinger interface
                                       ^
C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\src\main\java-templates\org\eclipse\paho\client\mqttv3\internal\ClientComms.java:210: warning: no @param for force
        public void close(boolean force) throws MqttException {
                    ^

Command line was: C:\oracle\Java\jdk1.8.0_131\jre\..\bin\javadoc.exe @options @packages

Refer to the generated Javadoc files in 'C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\target\apidocs' dir.

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: MavenReportException: Error while generating Javadoc:
Exit code: 1 - C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\src\main\java\org\eclipse\paho\client\mqttv3\ScheduledExecutorPingSender.java:28: error: reference not found
 * <p>This class implements the {@link IMqttPingSender} pinger interface
                                       ^
C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\src\main\java-templates\org\eclipse\paho\client\mqttv3\internal\ClientComms.java:210: warning: no @param for force
        public void close(boolean force) throws MqttException {
                    ^

Command line was: C:\oracle\Java\jdk1.8.0_131\jre\..\bin\javadoc.exe @options @packages

Refer to the generated Javadoc files in 'C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\target\apidocs' dir.

        at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.failOnError(AbstractJavadocMojo.java:6082)
        at org.apache.maven.plugin.javadoc.JavadocJar.execute(JavadocJar.java:192)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.apache.maven.reporting.MavenReportException:
Exit code: 1 - C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\src\main\java\org\eclipse\paho\client\mqttv3\ScheduledExecutorPingSender.java:28: error: reference not found
 * <p>This class implements the {@link IMqttPingSender} pinger interface
                                       ^
C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\src\main\java-templates\org\eclipse\paho\client\mqttv3\internal\ClientComms.java:210: warning: no @param for force
        public void close(boolean force) throws MqttException {
                    ^

Command line was: C:\oracle\Java\jdk1.8.0_131\jre\..\bin\javadoc.exe @options @packages

Refer to the generated Javadoc files in 'C:\Users\39608\Downloads\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\target\apidocs' dir.

        at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeJavadocCommandLine(AbstractJavadocMojo.java:5188)
        at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:2075)
        at org.apache.maven.plugin.javadoc.JavadocJar.execute(JavadocJar.java:188)
        ... 21 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.eclipse.paho.client.mqttv3
C:\Users\39608\Downloads\paho.mqtt.java-master>

**Comment by jpwsutton** [comment]
Not sure why this issue is being thrown as the MqttPingSender Interface definitely exists (https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttPingSender.java) Have you tried pulling the latest source and running a maven clean on it?

**Comment by jpwsutton** [comment]
No update since 2017, closing.

**Comment by SrEduardo** [comment]
I had the same error while building the Version 1.2.0 ( Master Branch) with maven, on UBUNTU 16.04:


`1 error`
`1 warning`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Reactor Summary:`
`[INFO] `
`[INFO] Eclipse Paho 1.2.0 ................................. SUCCESS [  0.399 s]`
`[INFO] org.eclipse.paho.client.mqttv3 ..................... FAILURE [  9.789 s]`
`[INFO] org.eclipse.paho.client.mqttv3.test ................ SKIPPED`
`[INFO] org.eclipse.paho.client.eclipse.view ............... SKIPPED`
`[INFO] org.eclipse.paho.client.eclipse.feature ............ SKIPPED`
`[INFO] Paho P2 Repository ................................. SKIPPED`
`[INFO] org.eclipse.paho.mqtt.utility ...................... SKIPPED`
`[INFO] org.eclipse.paho.ui ................................ SKIPPED`
`[INFO] org.eclipse.paho.ui.core ........................... SKIPPED`
`[INFO] org.eclipse.paho.ui.app ............................ SKIPPED`
`[INFO] org.eclipse.paho.ui.plugin 1.2.0 ................... SKIPPED`
`[INFO] ------------------------------------------------------------------------`
`[INFO] BUILD FAILURE`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Total time: 34.960 s`
`[INFO] Finished at: 2018-09-02T01:37:21+01:00`
`[INFO] ------------------------------------------------------------------------`
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project org.eclipse.paho.client.mqttv3: MavenReportException: Error while generating Javadoc: `
`[ERROR] Exit code: 1 - /home/sre/GK/Raspberry Pi/paho.mqtt.java-master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/ScheduledExecutorPingSender.java:28: error: reference not found`
`[ERROR]  * <p>This class implements the {@link IMqttPingSender} pinger interface`
`[ERROR]                                        ^`
`[ERROR] /home/sre/GK/Raspberry Pi/paho.mqtt.java-master/org.eclipse.paho.client.mqttv3/src/main/java-templates/org/eclipse/paho/client/mqttv3/internal/ClientComms.java:210: warning: no @param for force`
`[ERROR] 	public void close(boolean force) throws MqttException {`
`[ERROR] 	            ^`
`[ERROR] `
`[ERROR] Command line was: /usr/lib/jvm/java-8-oracle/jre/../bin/javadoc @options @packages`
`[ERROR] `
`[ERROR] Refer to the generated Javadoc files in '/home/sre/GK/Raspberry Pi/paho.mqtt.java-master/org.eclipse.paho.client.mqttv3/target/apidocs' dir.`
`[ERROR] `
`[ERROR] -> [Help 1]`
`[ERROR] `
`[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.`
`[ERROR] Re-run Maven using the -X switch to enable full debug logging.`
`[ERROR] `
`[ERROR] For more information about the errors and possible solutions, please read the following articles:`
`[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`
`[ERROR] `
`[ERROR] After correcting the problems, you can resume the build with the command`
`[ERROR]   mvn <goals> -rf :org.eclipse.paho.client.mqttv3`



Then I noticed this:


`[ERROR] Exit code: 1 - /home/sre/GK/Raspberry Pi/paho.mqtt.java-master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/ScheduledExecutorPingSender.java:28: error: reference not found`
`[ERROR]  * <p>This class implements the {@link IMqttPingSender} pinger interface`
`[ERROR]                                        ^`


And opened `/home/sre/GK/Raspberry Pi/paho.mqtt.java-master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/ScheduledExecutorPingSender.java` with a text editor, went to line 28 `  * <p>This class implements the {@link IMqttPingSender} pinger interface`, deleted the "i" in "IMqttPingSender", because there's no class with that name on the folder, only a class named "MqttPingSender".


After this, maven was able to build the package with no errors.

Don't really know why it worked. The line 28 belongs to a commented block of lines:
`/**`
 `* Default ping sender implementation`
 `*`
 `* <p>This class implements the {@link MqttPingSender} pinger interface`
 `* allowing applications to send ping packet to server every keep alive interval.`
 `* </p>`
 `*`
 `* @see MqttPingSender`
 `*/`

**Comment by rahulbommaraju** [comment]
I'm having the same error, are there any solution to solve this .
Here is the error, please give me a solution


`
1 error
1 warning
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.827 s
[INFO] Finished at: 2018-11-18T10:06:05+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project org.eclipse.paho.client.mqttv3: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - D:\my utils\java paho mqtt\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\src\main\java\org\eclipse\paho\client\mqttv3\ScheduledExecutorPingSender.java:28: error: reference not found
[ERROR]  * <p>This class implements the {@link IMqttPingSender} pinger interface
[ERROR]                                        ^
[ERROR] D:\my utils\java paho mqtt\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\src\main\java-templates\org\eclipse\paho\client\mqttv3\internal\ClientComms.java:210: warning: no @param for force
[ERROR] 	public void close(boolean force) throws MqttException {
[ERROR] 	            ^
[ERROR] 
[ERROR] Command line was: "C:\Program Files\Java\jdk1.8.0_181\bin\javadoc.exe" @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in 'D:\my utils\java paho mqtt\paho.mqtt.java-master\org.eclipse.paho.client.mqttv3\target\apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`
