### ISSUE TITLE
Invalid Subscripton Identifier allowed on SUSBSCRIBE

### ISSUE THREAD

**Issue by borgendale** [eclipse-paho/paho.mqtt.java#460]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [x] Bug exists in MQTTv5 Version (mqttv5-new Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

The MqttProperties class will create an invalid SUBSCRIBE packet in any case where a list containing more that one Subscription Identifier is specified.  Currently the class does not know if the packet it is creating the packet for is a PUBLISH packet which allows multiple or a SUBSCRIBE packet which only allows one.  However, since the PUBLISH packet with Subscription Identifiers is only sent by the server, the Paho client only needs to write the single value of the SUBSCRIBE packet.

It also is a usability issue that to set the subscriptionID on a subscribe, you need to create a List with one item in it, and set it into an MqttProperties object which you then send on the subscribe() action.

**Comment by jpwsutton** [comment]
I've re-jigged the MqttProperties API to have an extra pair of getters / setters:

- `public List<Integer> getSubscriptionIdentifiers()` (PUBLISH)
- `public void setSubscriptionIdentifiers(List<Integer> subscriptionIdentifiers)` (PUBLISH)
- `public Integer getSubscriptionIdentifier()` (SUBSCRIBE)
- `public void setSubscriptionIdentifier(Integer subscriptionIdentifier)` (SUBSCRIBE)

The Javadoc for each method explicitly states whether it is for a PUBLISH or SUBSCRIBE and the encoding process has been tweaked so that SUBSCRIBE packets cannot have more than one Subscription Identifier.
