### ISSUE TITLE
automaticReconnect reconnects every second instead of slowing down

### ISSUE THREAD

**Issue by viulian** [eclipse-paho/paho.mqtt.java#519]
Please fill out the form below before submitting, thank you!

- [X] Bug exists Release Version 1.2.0 ( Master Branch)

There are two ways in which the MQTT client can get disconnected and automaticReconnect is triggered:
a) connection to MQTT server is broken.
b) an Exception is thrown from the messageArrived(...) implementation.

In the case of loosing connection to MQTT server, the reconnectDelay does seem to increase, and attempts to reconnect slow down.

However, in case of Exception thrown in messageArrived, the reconnect attempt is done every second instead of slowing down.

I would like on the MQTT server to keep the message until the application can process it. If temporarily the application cannot handle the message (by throwing an Exception in messageArrived), the MQTT client is disconnected. 
But since the MQTT server connection is established successfully, the reconnectDelay is also reset (I suspect). Which means that if the application cannot handle the message for few minutes, hundreds of reconnects will happen.

I guess that I could just try to persist the message locally, but then it defeats the purpose of the MQTT server doing the queue-ing and persistence until the client can successfully pick up the message.

**Comment by jpwsutton** [comment]
Hi @viulian,

It feels like we might be looking at the wrong issue here.. I think resetting the reconnect timeout when a successful connection has been made is the right thing to do because assuming that the connection can successfully be made, there is no reason to delay in almost all use cases.

I appreciate that I don't know about the application that you are building, but have you considered moving all incoming messages to a separate queue that the application can then process at it's leisure? That way, you can return the messageArrived callback immediately and not block any more incoming messages. Assuming you're using QoS 2, if you delay connecting for a while, you could find that as soon as you connect, the server will attempt to deliver another batch of messages that would immediately overload your client again.

**Comment by viulian** [comment]
Home environment, VMs may get restarted; I'm writing a Java mqtt client that consumes messages from a local mqtt broker and sends them to a carbon-cache (Graphite backend) in a different VM.

If the Graphite VM goes down, I would like the messages to remain persisted on the mosquitto server. Once the VM gets back, the client should reconnect and start sending the failed message plus any new ones. I like a lot this robustness (throw Exception and the mqtt message is not acknowledged to the broker).

While I understand the suggestion to create another queue locally, the mosquitto server already has it and I'd like to use it - it would be redundant in my case. Plus, the same problem (in theory) remains: if the separate queue encounters a problem, the client will just attempt every second to write to it. I do prefer to let mosquitto handle the safe keeping of the messages and I'll accept 120 log lines (stack trace suppressed) in 2 minutes - than having to write the queue though :)

Thought I'd mention that it would be nice if the API would slow down reconnects no matter what triggered them (broker connection lost OR Exception in messageArrived()).

**Comment by icraggs** [comment]
You can implement your own reconnect behaviour by switching off auto-reconnect and using the connectionLost() callback.

**Comment by icraggs** [comment]
I think implementing your own reconnect behaviour is probably the best solution.
