### ISSUE TITLE
Null Pointer Exception using Memory Persistence

### ISSUE THREAD

**Issue by djbr-david** [eclipse-paho/paho.mqtt.java#522]
Please fill out the form below before submitting, thank you!

- [X] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

Using Memory Persistence and am getting the above exception when calling the close method, but other methods could suffer the same issue. The setup code is:
```
            persistence = new MemoryPersistence();
            client = new MqttClient(host, clientId, persistence);

```
which generally works fine, but if the MqttClient fails to initialise, the persistence open method wont be called so later on when I try to call the close method as part of my disconnect handling it fails. Checking the File Persistence code, I see this situation is handled correctly, so for consistency Memory Persistence should exhibit the same behaviour which then means client code doesn't need to change if the underlying Persistence mechanism changes.

**Comment by jpwsutton** [comment]
Thanks for raising this issue @djbr-david, I've put a check in that will only attempt to close the Persistence layer if the hashtable has been initialised, I've also ported some improvements that are in the v5 client that throw an `MqttPersistenceException` when putting or getting if the persistence hasn't been initialised, so that should get rid of any null pointers would would have otherwise seen too.

**Comment by djbr-david** [comment]
Many thanks for your time and effort.
