### ISSUE TITLE
ClientState.java seems to mix up ms and ns in line 790

### ISSUE THREAD

**Issue by hagego** [eclipse-paho/paho.mqtt.java#738]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.2.2 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)

During debugging of a strange behavior with respect to pings (actually on Android where timing system is not working well) I found that line 790 in ClientState.java seems to mix up milli and nano seconds.

The correct implementation should be

`nextPingTime = Math.max(1,  (keepAlive - (time - lastOutboundActivity))/1000000); // milliseconds needed for nextPingTime`

**Comment by rdasgupt** [comment]
@hagego Good catch. 
I think your branch is not current. Your proposed code change doesn't match with current code in 1.2.2 master or develop. In your code, if you have used keepAlive for calculating or setting nextPingTime in all statements where nextPingTime is set, then your fix is correct. If getKeepAlive() is used (as in the current code), then your proposed fix requires some changes.

Let me explain:

In ClientState 
keepAlive variable is in nano seconds:
- setKeepAliveSecs() converts keepAlive interval from sec to nano and sets keepAlive
- getKeepAlive() returns value in Milliseconds

time is in nano seconds -- time = System.nanoTime()

lastOutboundActivity is in nano seconds - check notifySent() and notifySendBytes() --- this.lastOutboundActivity = System.nanoTime();

The nextPingTime is used to schedule MqttPingerSender that takes ping interval in milli. 
The nextPingTime is set in three statements. Unit used is not consistent.

long nextPingTime = this.keepAlive;    
---- initialized using keepAlive value which is in nano. This should be set using getKeepAlive()

nextPingTime = getKeepAlive();           
---- set using getKeepAlive() that returns value in milli
nextPingTime = Math.max(1,  getKeepAlive() - (time - lastOutboundActivity));  <---- set using getKeepAlive() that returns value in milli, but time and lastOutboundActivity in nao.

So the correct fix should be:
long nextPingTime = getKeepAlive();

and

nextPingTime = Math.max(1,  getKeepAlive() - (time - lastOutboundActivity)/1000000);

**Comment by hagego** [comment]
Hi @rdasgupt ,
yes I see. The keepalive probably came into my code during debug. Anyway, the problem is the same.
BTW, while this fix prevents a kind of endless loop on Android, more changes were needed to make the ping somewhat work - System.nanoTime() simply is unusable on this platform ;-(

**Comment by rdasgupt** [comment]
Hi @hagego 
I don't see any reason to use nanoTime for nextPingTime calculation and then converting back to milli for setting up the timer. The KeepAlive interval, an user can specify is in seconds. I don't understand why do we need nanoSecond granularity to set "time" and "lastOutboundActivity" in nano.
We can change the code to use milli. We may have to make additional changes if we use milli. I will propose a PR. I will incorporate changes suggested by you,  if needed.

**Comment by rdasgupt** [comment]
Duplicate of #640

**Comment by rdasgupt** [comment]
We will have to keep the time in nano. Since wall clock can be set by the users, the system currentTimeMillis may jump unpredictably. The clock used for system nanoTime, is guaranteed to be monotonic and well suited for interval timing. Proposal in #640 is the best solution for the current issue. There is no need to keep delta.

**Comment by rdasgupt** [comment]
Fix is provided by PR #746

**Comment by rdasgupt** [comment]
PR #746 is merged.

**Comment by barondodd** [comment]
I believe this issue is also the likely a large contributing cause to a lot of random disconnections I have seen on a customer site.

**The broker must disconnect a client that does not send a message or a PINGREQ packet in one and a half times the keep alive interval**

In customer logs I would see a lot of weird calculations for the next ping time, such as with a keep alive of 60 seconds:

Schedule next ping at 232,400
or
Schedule next ping at 194,000

When really the max value this should be is 60'000. Many occurrences of this per day.

`nextPingTime = Math.max(1, getKeepAlive() - (time - lastOutboundActivity));`

My theory is that notifySentBytes() is being called by another thread _just after_ time has been calculated a few lines up, so that lastOutboundActivity is a fraction of 1 second larger than time, meaning we are subtracting a negative from keepAlive, meaning we are really adding to keepAlive. This results in a value larger than 1.5 x the keep alive period and the broker dumps the connection.

This is exacerbated by the fact that the original issue of the nextPingTime being calculated at 1 most of the time, as it means we are going through this calculation 100's of times per second, meaning we are more likely to experience the timing issue.

Should we not have a min(getKeepAlive(), nextPingTime ) just for sanity in case of timing or clock change issues?
