### ISSUE TITLE
[Question] How to get detailed reason code for disconnection or failure? 

### ISSUE THREAD

**Issue by iAmSKU** [eclipse-paho/paho.mqtt.java#749]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.2 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

Hi, 

I am using library to connect to various cloud provider.

I am using debug library to get MQTT log and also java net logging for detailed message communication. 

**But for end user it's really difficult to analyse and understand MQTT logs or network logs.**

Is there any way to capture actual error reason for the disconnection (For example DUPLICATE_CLIENT_ID or AUTHENTICATION_FAILURE etc) when connection lost or publish failed with bellow callback?

```
@Override
public void connectionLost(Throwable cause) {
//Returns 32109
System.log.println(cause);
}
```

**Comment by rdasgupt** [comment]
@iAmSKU 
You can get associated message with the exception:
System.out.printf(String.format("Connection to Server is lost: %s.\n", cause.getMessage()));

Paho client v1.2.x supports MQTT v3. Some of the messages (in this version) associated with an exception are easy to understand. For example:
**Timed out waiting for a response from the server.**
**Not authorized to connect**
But it may be difficult to know the root cause from some of the exception message. For example:
**Connection lost.**

If both MQTT client and broker are MQTT v5 compliant, you can get errors returned by the server. For example duplicate client ID. 

Paho client compliant to MQTT v5 is not released yet. Development and test work is in progress. However, you can build and try this version:
https://github.com/clipse/paho.mqtt.java/tree/master/org.eclipse.paho.mqttv5.client
You can use "test.mosquitto.org" broker, to try MQTT v5 features.

**Comment by iAmSKU** [comment]
Thanks @rdasgupt.

I have tested my code with changes its perfectly working fine... 

I will work on MQTTv5 solution... 

Thanks again for your valuable response.

**Comment by mingweipactera** [comment]
I have encountered the same problem, could you tell me how did you solve it?
